id: search_empty
learningObjectives: 
- Handling edge cases
hints:
- Make sure the div with the id `empty` is visible on the page when there are no results. 
- Remember to remove the empty div on start and only show it after an empty result has been returned. 
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Oh no, someone just searched for a dishwasher!
        delay: 1000
      - text: "A dishwasher! Who would want to buy a regular dishwasher?! Oh boy, we didn’t expect this to happen, like, ever. But some users just don’t know what’s good for them. I already checked with HR but they say we can’t punish them for it, so lets at least make sure we sternly reprimand them:"
        delay: 2700
      - text: "Please :instruction[**add an appropriate scolding text to the system,**] that will be displayed in the search results when a wayward user types in a string that doesn’t match any product in the system."
        delay: 7000
      - text: :instruction[**Make sure that it has the id `empty`**]
        delay: 
      - text: "Our designer said it should look something like this (don't dwell too much on the design, we only care about functionality right now):"
        delay: 2300
      - text: https://res.cloudinary.com/wilco/image/upload/v1669628851/anythink-assets/Images%20for%20quests/Search%20quest/search2_hcaplg.png
        delay: 1500
      - text: When you're ready, open a PR.
        delay: 1200

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Got it, will review in a sec. 

          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Got it, will review in a sec. 
                delay: 300
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Approved! Awesome job 😀. Go ahead and merge the PR.

          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Approved! Awesome job 😀. Go ahead and merge the PR.
                delay: 300
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Let’s try this again, shall we? **Make sure all [checks](${githubWorkflowRunUrl}) pass**.

          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Let’s try this again, shall we? **Make sure all [checks](${githubWorkflowRunUrl}) pass**.
                delay: 300
        github_pr_merged:
          do:
          - actionId: finish_step
githubActions:
  backend:
  frontend:
    capabilities:
    - jest-puppeteer
    - "puppeteer@18.1.0"
    testFile: "search-empty.test.js"
solution:
  do:
    - actionId: bot_message
      params:
        messages:
          - text: The `ItemList` component is responsible for presenting the list of the items.
          - text: Make sure you present it only if the user didn't use the search **or** there are one or more items to show.
          - text: Otherwise, show some text to the user, telling him that we don't have any items to show based on his search.
