id: search_secret_open_generic
hints:
- Glad you asked! Did you notice we already support some filtering for fetching items in our backend (for example, filter by tag)? You can add another filter by term.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "Wonderful ✨ The bang-up job you’re doing makes me proud of myself for thinking to allocate it to you! Now it’s time to hide all of your hard work so that only the worthy can access it. Let’s have the search box appear only after a visitor clicks the word “get” in our motto."
        delay: 2000
      - text: "Here’s an example of what it should look like:"
        delay: 1200
      - text: "![](https://media.giphy.com/media/cI06BN2gTdZx0VYmwP/giphy.gif)"
        delay: 2700
      - text: "Think you can do that? If so, go ahead, then send me one final PR for this assignment."
        delay: 500

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${githubPrLifecycleStatus}"
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: "Wonderful! I’ll check it ASAP."
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: "Looks great, that’s exactly what I was going for."
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: "That’s not it. Don’t worry, you have time to fix everything."
        github_pr_merged:
          do:
          - actionId: finish_step

githubActions:
  frontend:
    capabilities:
    - jest-puppeteer
    - puppeteer
    testFile: "search-secret-open.test.js"