id: search_endpoint
learningObjectives: 
- Creating an API endpoint 
hints:
- Glad you asked! Are you aware that our backend already supports some filtering options (for example, filter by tag)? You can add another filter by term.
- Our product manager insists that partial matches, not only exact matches, must be returned by the query. 
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Now (before we implement the full UI), we want to add the ability to filter by title!
        delay: 1500
      - text: So, first you need to :instruction[**add product filtering support to our API.**] In other words, when retrieving a list of items using a GET request, there should be an option to :instruction[**add a query parameter called “title”**], so that once we call this endpoint, the backend will show all the relevant items :instruction[**whose title `contains` the same title query**].
        delay: 1200
      - text: As usual, **open a PR when you’re done.**
        delay: 4000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Lovely. Let me take a look.
              
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Lovely. Let me take a look.
                delay: 300
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Looking good! Now we can move on to the UI. \nI'll send you more details in Snack.

          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Looking good! Now we can move on to the UI
                delay: 300
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Umm… something is not quite right, please take another look and try again.

          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Umm… something is not quite right, please take another look and try again.
                delay: 300
        github_pr_merged:
          do:
          - actionId: finish_step


githubActions:
  backend:
    capabilities:
    - axios
    - dotenv
    testFile: "filter.js"
