id: search_create_item
learningObjectives:
  - Manually adding an item to Anythink Market
hints:
  - Oh, OK! Maybe you should try to **find the page that lets you add new items.**
  - Still stuck, huh? Look for the button in the Anythink Market header.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: Nice! So you created a user on Anythink, but now you need to have something to search for. 
            delay: 2200
          - text: Go ahead, :instruction[**add a single item to the Marketplace**].
            delay: 2500
trigger:
  type: local_page_load
  flowNode:
    if:
      conditions:
        - conditionId: text_match_regex
          params:
            text: "${path}"
            regex: ^/item/
            flags: i
      then:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
                - text: Good! Although, I'm going to ignore the fact that from all of the possible items in the world, you chose to go with a ${Lodash.startCase(Lodash.dropRight(path.slice(6).split("-")).join("-"))}
                  delay: 2000
          - actionId: finish_step
solution:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: To add a new item go to the Anythink Market and click the "New Item" button in the header.
          - text: Add a title, a description, and an image (if you have one), and publish the item.
