id: search_secret_open
learningObjectives: 
- Conditional visibility of a UI component
hints: 
- Psst, are you sure you added a div with the `search-box` id?
- This component must be hidden when the page loads and only visible when clicked.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Wonderful ✨ The bang-up job you’re doing makes me proud of myself for thinking to allocate it to you! 
        delay: 2000
      - text: Now it’s time to hide all of your hard work so that only the worthy can access it. 
        delay: 700
      - text: :instruction[Let’s have the search box appear only after a visitor clicks the word “get” in our motto.]
        delay: 1500
      - text: "**Here’s an example of what it should look like:**"
        delay: 1200
      - text: "![](https://media.giphy.com/media/cI06BN2gTdZx0VYmwP/giphy.gif)"
        delay: 2700
      - text: Think you can do that? If so, :instruction[go ahead, then open one final PR for this assignment.]
        delay: 700

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Wonderful! I’ll check it ASAP.
              
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Wonderful! I’ll check it ASAP.
                delay: 300
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Looks great, that’s exactly what I was going for. Let's merge the PR!

          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Looks great, that’s exactly what I was going for. Let's merge the PR!
                delay: 300
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: That’s not it. Don’t worry, you have time to fix everything.

          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: That’s not it. Don’t worry, you have time to fix everything.
                delay: 300
        github_pr_merged:
          do:
          - actionId: finish_step

githubActions:
  frontend:
    capabilities:
    - jest-puppeteer
    - "puppeteer@18.1.0"
    testFile: "search-secret-open.test.js"
